name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip test')"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Python packages
      shell: bash
      run: pip3 install pytest wheelhouse wheeltools auditwheel
    - name: Start docker container
      shell: bash
      run: docker run --name manylinux -v `pwd`:/workspace -it -d quay.io/pypa/manylinux2014_x86_64 bash
    - name: Build wheel
      shell: bash
      run: docker exec -i manylinux bash -c "cd /workspace && /opt/python/cp310-cp310/bin/python setup.py build_ext -j 4 bdist_wheel"
    - name: Fix wheel
      shell: bash
      run: |
        wget https://github.com/Kuree/hgdb/raw/master/scripts/fix_wheel.py
        mkdir -p wheelhouse temp
        auditwheel repair dist/*.whl --plat manylinux_2_17_x86_64 -w temp
        python3 fix_wheel.py temp/*.whl -w wheelhouse
    - name: Install Python packages
      shell: bash
      run: pip3 install --no-index --find-links=wheelhouse hgdb-rtl
    - name: Upload wheel
      uses: actions/upload-artifact@v2
      with:
        name: hgdb-rtl
        path: wheelhouse/
    - name: Tests
      shell: bash
      run: |
        docker run --name test -v `pwd`:/workspace -it -d python:3.10 bash
        docker exec -i test bash -c "pip install pytest /workspace/wheelhouse/*.whl"
        docker exec -i test bash -c "cd /workspace && pytest tests/ -v"
    - name: Publish wheels to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: startsWith(github.ref, 'refs/tags')
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: wheelhouse
